### ISSUE TITLE
Avalanche Rosetta Node Upgrade

### ISSUE THREAD

**Issue by debasish22** [ava-labs/avalanche-rosetta#18]
Can you please provide some documentation on how to upgrade avalanche Rosetta Node when there is a latest release

**Comment by dhrubabasu** [comment]
It depends on your server installation. We publish dockerfiles regularly here: https://hub.docker.com/r/avaplatform/avalanche-rosetta/tags

If you clone the repo and run from a binary, you can follow the directions here: https://github.com/ava-labs/avalanche-rosetta#installation
