### ISSUE TITLE
Rosetta node is not running

### ISSUE THREAD

**Issue by debasish22** [ava-labs/avalanche-rosetta#19]
Hello Team,

I have followed the steps as mentioned and tried to run rosetta node, container started but stopped after few seconds. Below are the logs from the main.log file. Can you please help why the container is not running.

INFO [07-20|09:17:49] app/process/process.go#126: bootstrapped with current database version: false
WARN [07-20|09:17:49] app/process/process.go#185: UPnP or NAT-PMP router attach failed, you may not be listening publicly. Please confirm the settings in your router
INFO [07-20|09:17:49] node/node.go#996: node version is: avalanche/1.4.10
INFO [07-20|09:17:49] node/node.go#997: node ID is: NodeID-3uh5kzAJP7at96VYbcFKBznPGD8MHnCyz
INFO [07-20|09:17:49] node/node.go#998: current database version: v1.4.5
INFO [07-20|09:17:49] node/node.go#505: initializing API server
INFO [07-20|09:17:49] api/server/server.go#82: API created with allowed origins: [*]
INFO [07-20|09:17:49] node/node.go#804: initializing metrics API
INFO [07-20|09:17:49] api/server/server.go#207: adding route /ext/metrics
INFO [07-20|09:17:49] node/node.go#767: initializing keystore
INFO [07-20|09:17:49] node/node.go#779: skipping keystore API initialization because it has been disabled
INFO [07-20|09:17:49] node/node.go#759: initializing SharedMemory
INFO [07-20|09:17:49] node/node.go#168: this node's IP is set to: "172.17.0.3:9651"
INFO [07-20|09:17:49] node/node.go#885: initializing Health API
INFO [07-20|09:17:49] api/server/server.go#207: adding route /ext/health
INFO [07-20|09:17:49] node/node.go#551: initializing VM aliases
INFO [07-20|09:17:50] api/server/server.go#207: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [07-20|09:17:50] api/server/server.go#207: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [07-20|09:17:50] api/server/server.go#207: adding route /ext/vm/mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6/ws
INFO [07-20|09:17:50] api/server/server.go#207: adding route /ext/vm/mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6/rpc
INFO [07-20|09:17:50] node/node.go#820: skipping admin API initialization because it has been disabled
INFO [07-20|09:17:50] node/node.go#858: initializing info API
INFO [07-20|09:17:50] api/server/server.go#207: adding route /ext/info
INFO [07-20|09:17:50] node/node.go#935: skipping ipc API initialization because it has been disabled
INFO [07-20|09:17:50] node/node.go#948: initializing chain aliases
INFO [07-20|09:17:50] node/node.go#966: initializing API aliases
INFO [07-20|09:17:50] node/node.go#834: skipping profiler initialization because it has been disabled
INFO [07-20|09:17:50] node/node.go#491: initializing chains
INFO [07-20|09:17:50] chains/manager.go#239: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [07-20|09:17:51] api/server/server.go#113: HTTP API server listening on "0.0.0.0:9650"
INFO [07-20|09:17:51] api/server/server.go#191: adding route /ext/bc/11111111111111111111111111111111LpoYY
FATAL[07-20|09:18:49] node/node.go#215: Failed to connect to bootstrap nodes. Node shutting down...
INFO [07-20|09:18:49] node/node.go#1087: shutting down node with exit code 1
INFO [07-20|09:18:49] ipcs/chainipc.go#101: shutting down chain IPCs
INFO [07-20|09:18:49] chains/manager.go#762: shutting down chain manager
INFO [07-20|09:18:49] snow/networking/router/chain_router.go#185: shutting down chain router
INFO [07-20|09:18:49] network/network.go#983: shutting down network
INFO [07-20|09:18:49] node/node.go#1111: cleaning up plugin subprocesses
INFO [07-20|09:18:49] node/node.go#1114: finished node shutdown
INFO [07-20|09:18:49] nat/nat.go#152: Unmapped all ports

**Comment by dhrubabasu** [comment]
We've performed several updates to AvalancheGo and avalanche-rosetta since this issue was opened. Please try a recent version of rosetta!
