### ISSUE TITLE
Miss matching transaction count in C-Chain block 3010277 

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanche-rosetta#35]
Hello Team,

As from explorer block 3010277 contains six transaction while query rosetta, **why I am getting seven transactions**?
Why seventh transaction is import TransactionType operation? 
Explorer Url : https://cchain.explorer.avax.network/blocks/3010277/transactions
Rosetta Query input -:
{
    "network_identifier":  {
        "blockchain": "Avalanche",
        "network": "Mainnet"
    },
    "block_identifier": {
        "index":3010277
    }
}
Url : http://127.0.0.1:9650/block
Output 👎 
![image](https://user-images.githubusercontent.com/29591202/130740805-198453f6-c498-4ac5-bd3e-629d538e0810.png)

**Comment by dhrubabasu** [comment]
The seventh transaction is an atomic transaction. You are seeing six transactions on snowtrace as they do not index atomic transactions.
