### ISSUE TITLE
Perform TransactionHash search avalanche-rosetta

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanche-rosetta#37]
Hello Team,
**How to perform TransactionHash search avalanche-rosetta? 
If not implemented, is there any plan to implement it in coming weeks?**

**Comment by dhrubabasu** [comment]
As of now, there are no plans to add the optional "indexer" endpoints of Rosetta (which allow this functionality) https://www.rosetta-api.org/docs/SearchApi.html

If you'd like to make a PR, happy to review and get it merged in!
