### ISSUE TITLE
validation error:genesis block hash is not provided

### ISSUE THREAD

**Issue by sergemastaki** [ava-labs/avalanche-rosetta#56]
Hi. I tried to run avalanche-rosetta on my local machine. I followed the instructions at https://github.com/ava-labs/avalanche-rosetta. But I get that error:
`2021/11/30 14:32:22 config validation error:genesis block hash is not provided.`
My config file is:
 `{
  "rpc_endpoint": "https://api.avax-test.network",
  "mode": "online",
  "listen_addr": "0.0.0.0:8080",
  "network_name": "Fuji",
  "chain_id": 43113,
  "log_requests": true
}`

**Comment by dhrubabasu** [comment]
You need to provide the `genesis_block_hash` key as shown here: https://github.com/ava-labs/avalanche-rosetta#usage
